language: python
sudo: false
python:
- 2.7
- 3.5
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-system-dev
    - libboost-test-dev
    - libboost-thread-dev
    - libzmq3-dev
install:
- cd control
- python setup.py --stub-only install
- pip install --install-option='--stub-only' -e .[test]
- pip install coveralls
script:
- python setup.py --stub-only nosetests
- coverage report -m
after_success:
- coveralls
notifications:
  slack:
    secure: kKmPRPxIkhTf5wQR+KYtmid7FHD29OwQMdYYyMNzUdVHk4QJZ4SW32Jt5IHemY4V/PgTRmTvSwDDsjYV3y9rExdCAQgKfaLSLdRkZFR7FIGNWRCJ2GoCSB8I/gT9HfayoLaOGiE1EJG4S3WMdqShUNgEdraTuZ8byzOM50qKyKGeYMVGxo7DI+AmgSznEKQ6zWP4nqZuY7S0ns8hf42s0TQUsnfPFpfKfZtpxtl1cTbM2P4g8iKdhNPgBAfZis8/o2w+pZEmKoTeAUepkt/7V6H0TD8OjHEWpC4n0TydU/BKu/SgSqp/t6hFUTr7V5zN265I4dLwWz/mcTO1NV17f24DIiGPOemaG45xqtbj400X4xEUpvTjgchKIE1AAZGJnDdybGh15AvmCg5/jYQPL9pDO8JCEqfLUdUYQqKZpUumwwFOl7Ck1ESuHmb+pld+2xPa8sK2pdclDL+9lrbzvF2BfQ1bdrn4RU5LyYaYa9/l4Tbjn5z3ubpMQorslD7GFy4X6fu5R9VTfxxN8DS51j889lKQ7h5ZODz8Ohhock3OeqHXZUKygJWXQR9Q2xXdr3nFVleOzY6/2oIIwfmh/95FOIBC2z2CPUjNHp5gGsVMyFQh9fGnriHFb5nhn1aVMR9QzwVjVn7hPXwoXfCn2q4nF2OV2GAFGCEiwQZEDR4=
